action_repeat: 2
discount: 0.99
num_train_frames: 1000000
bc_freq: 0
warmup: 2000
eval_every_frames: 2000
num_eval_episodes: 50
rollout_length: 4096
batch_size: 64
pretrain_steps: 10000
replay_buffer_size: 100000
replay_buffer_num_workers: 4
nstep: 1
save_snapshot: false
seed: 2
device: cuda
save_video: false
use_wandb: true
wandb_project: metaworld
wandb_entity: null
wandb_group: on_policy
experiment: ppo_exp
lr: 0.0003
agent:
  _target_: on_policy.PPOAgent
  obs_shape: ???
  action_shape: ???
  device: ${device}
  lr: ${lr}
  batch_size: ${batch_size}
  hidden_dim: 64
  clip_eps: 0.1
  ppo_epochs: 3
  value_coef: 0.5
  entropy_coef: 0.01
  reverse_kl_coef: 0.01
  gae_lambda: 0.99
  gamma: 0.99
