action_repeat: 2
discount: 0.99
num_seed_frames: 0
utd: 1
bc_freq: 2
num_train_frames: 300000
eval_every_frames: 2000
num_eval_episodes: 50
save_snapshot: true
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
warmup: 2000
seed: 1
device: cuda
save_video: false
use_wandb: true
wandb_project: metaworld
wandb_entity: null
wandb_group: off_policy
experiment: exp
lr: 0.0001
agent:
  _target_: off_policy.ACAgent
  obs_shape: ???
  action_shape: ???
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.005
  hidden_dim: 256
  num_critics: 2
  stddev_clip: 0.3
